### ISSUE TITLE
data download error

### ISSUE THREAD

**Issue by mjwang1010** [wcornwell/leaf13C#1]
Hi, thanks for your data sharing! But when I tried to download the data as it said, an error occurred and said "Error: key '0.1.0' ('objects') not found, with error: Timeout was reached" after I typed "leaf13C::get_data()". I'm not sure if it is the program issue or my connection problem.
My OS: macOS Sierra version 10.12.6
R version: 3.3.2

**Comment by wcornwell** [comment]
hmmmm it's working for me.  Seems like it could be either internet connection or a firewall issue?  is that possible?

**Comment by mjwang1010** [comment]
Thanks. I tried again later. It worked! I'm afraid it's just an internet connection issue.
